### ISSUE TITLE
Next-Generation onion services (v3) support

### ISSUE THREAD

**Issue by Alicesland** [DonnchaC/onion-balance#69]
Now that we have a stable release of the 0.3.2 branch next-generation (v3) onion services are hitting the mainstream! onionbalance, in it's current design, does not support v3 onion services. 

Being that v3 onion services are the future, it makes sense that onionbalance should work on supporting them. 

I'm not sure if you guys allow bounties on this git but it's very important personally that onionbalance supports v3 onion services. I'm willing to provide a reward ($1000+), payed in cryptocurrency, for the brave soul who submits a pull request accomplishing just that.

**Comment by alecmuffett** [comment]
Linking from a Reddit discussion:

https://www.reddit.com/r/TOR/comments/82ep61/how_can_i_keep_my_onion_v3_private_publuic_keys/dvabdfm/

> OnionBalance requires STEM support for V3, before it can be updated (possibly a substantial rewrite will be needed) to support the new format onions. It's not only a matter of "longer addresses" but also a matter of cross-signing the descriptors to support new-style cryptography, so in fact it might be safest to create a new, separate OnionBalance for V3.
>
>So: STEM needs updating and testing for V3, and then OnionBalance needs to support the new STEM library and encryption. Then (for me) EOTK needs to support the new OnionBalance.
>
>I am not expecting a solution to ship until 2019, earliest.

**Comment by asn-d6** [comment]
See https://trac.torproject.org/projects/tor/ticket/26768 for the respective torproject trac ticket.

**Comment by cretz** [comment]
There was discussion on the mailing list about this, see https://lists.torproject.org/pipermail/tor-dev/2018-April/013128.html. https://trac.torproject.org/projects/tor/ticket/25417 is the ticket to watch.

Also shameless plug, if a "substantial rewrite is needed" and you want to switch languages to something like Go, I wrote https://github.com/cretz/bine which has a goal of feature parity with Stem.

**Comment by traumschule** [comment]
Linked this from [Tor's new community projects page](http://ea5faa5po25cf7fb.onion/projects/tor/ticket/16576)

**Comment by duritong** [comment]
There is a new STEM release available: https://stem.torproject.org/change_log.html#version-1-8

**Comment by afshar-mohammad** [comment]
Any updates on this? Oh man I really need it for v3.

**Comment by asn-d6** [comment]
I'm currently working on this. Please expect a release around March :)

**Comment by asn-d6** [comment]
Please see https://lists.torproject.org/pipermail/tor-dev/2020-January/014142.html for initial testing instructions.

**Comment by asn-d6** [comment]
The alpha testing guide has moved to git:  https://github.com/asn-d6/onionbalance/blob/master/docs/alpha-testing-v3.txt

**Comment by adrelanos** [comment]
Quote https://blog.torproject.org/cooking-onions-reclaiming-onionbalance

> we just added v3 support for Onionbalance

**Comment by asn-d6** [comment]
Yes indeed. I'm still waiting for a bit of testing feedback before I replace the actual pip/debian packages with the new onionbalance.

So, please, if you test this let me know so that I get more confidence that I haven't broken anything.

**Comment by asn-d6** [comment]
This has been implemented. Closing.
